name: Print Software Versions

on:
  push:
    branches: [main]

jobs:
  PrintDataProcessingSoftwareVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Operating System
        run: uname -a

      - name: Install Python
        run: sudo apt-get install -y python3

      - name: Print Python Version
        run: python3 --version

      - name: Install Django
        run: pip3 install django

      - name: Print Django Version
        run: django-admin --version

  PrintDatabaseSoftwareVersion:
    runs-on: ubuntu-latest
    needs: [PrintDataProcessingSoftwareVersions]
    steps:
      - name: Install MySQL Client
        run: sudo apt-get install -y mysql-client

      - name: Print MySQL Version
        run: mysql --version

