name: Data Schema Code Convention

on:
  push:
    branches:
      - main

jobs:
  json_schema_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install JSON Linter
        run: npm install -g @prantlf/jsonlint

      - name: Run JSON Linter on Data Schema
        run: jsonlint $GITHUB_WORKSPACE/DataSchemaModified.json
